import { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { ArrowRight, HelpCircle } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Frequently Asked Questions | HygieneFix',
  description: 'Common questions about food hygiene ratings, reinspections, SFBB, and how HygieneFix works. Get answers to improve your food safety score.',
};

const FAQS = [
  {
    q: 'What is HygieneFix?',
    a: 'HygieneFix is a tool that checks your food hygiene rating using official FSA data and generates a personalised action plan showing exactly what to improve before your next inspection. The rating check is free; the detailed action plan costs £49.',
  },
  {
    q: 'How does HygieneFix get my food hygiene rating?',
    a: 'We pull data directly from the Food Standards Agency (FSA) public register in real time. This is the same data shown on the FSA website at ratings.food.gov.uk. We use it under the Open Government Licence v3.0.',
  },
  {
    q: 'What is a food hygiene rating?',
    a: 'The Food Hygiene Rating Scheme (FHRS) rates food businesses from 0 (Urgent Improvement Necessary) to 5 (Very Good) based on food handling hygiene, structural condition of premises, and confidence in management. Inspections are conducted by Environmental Health Officers from your local authority.',
  },
  {
    q: 'What do the individual scores mean?',
    a: 'Your rating is based on three scores: Hygiene (0–25, lower is better) covers food handling and preparation. Structural (0–25, lower is better) covers premises condition and cleanliness. Confidence in Management (0–30, lower is better) covers documentation, training, and food safety systems. The combination determines your 0–5 rating.',
  },
  {
    q: 'Is the action plan written by a human?',
    a: 'The action plan is generated by AI based on FSA inspection criteria, your specific scores, and your business type. It is not written by a human consultant. While it provides detailed, practical guidance, it is not a substitute for professional advice from a qualified Environmental Health Professional. Our terms of service include full details.',
  },
  {
    q: 'How can I improve my food hygiene rating?',
    a: 'Focus on the area where you scored worst. For most businesses rated 0–2, the management score is the primary drag — meaning SFBB documentation, temperature logs, cleaning schedules, and training records need attention. A HygieneFix action plan shows you exactly which improvements to prioritise for your specific scores.',
  },
  {
    q: 'Can I request a reinspection?',
    a: 'Yes. In England, Wales, and Northern Ireland, you can request a paid reinspection from your local authority at any time after making improvements. Fees are typically £150–300, and most authorities aim to visit within 3 months. In Wales, this right is statutory. Scotland operates a different scheme (FHIS) with different procedures.',
  },
  {
    q: 'What is SFBB (Safer Food Better Business)?',
    a: 'SFBB is a free food safety management system published by the Food Standards Agency for small food businesses. It covers food safety procedures ("safe methods") and includes a diary for ongoing records. Environmental Health Officers expect to see an active, maintained SFBB pack during inspections. Download it free from food.gov.uk.',
  },
  {
    q: "What is Natasha's Law?",
    a: "Natasha's Law (in force since October 2021) requires all food that is prepacked for direct sale (PPDS) — such as sandwiches and salads made and packaged on your premises — to carry a full ingredients list with the 14 major allergens clearly emphasised. Non-compliance is both a food safety and legal risk.",
  },
  {
    q: 'Do I legally have to display my food hygiene rating?',
    a: 'In Wales, yes — the Food Hygiene Rating (Wales) Act 2013 makes display mandatory, with penalties for non-compliance. In England and Northern Ireland, display is voluntary but strongly encouraged. The FSA has been campaigning for mandatory display across the UK.',
  },
  {
    q: 'Will delivery platforms remove me for a low rating?',
    a: 'Deliveroo has removed businesses rated 0 from its platform. Just Eat and Uber Eats have similar policies with minimum rating thresholds. For businesses that generate significant revenue through delivery platforms, a low rating poses a direct financial risk.',
  },
  {
    q: 'How does HygieneFix handle my data?',
    a: 'We process your business information (name, address, rating) from the FSA public register. If you purchase an action plan, Stripe handles payment processing and we use your email address to deliver the PDF. We do not sell or share your data. Full details are in our Privacy Policy.',
  },
  {
    q: 'Can I get a refund?',
    a: 'Because the action plan is generated and delivered digitally immediately after purchase, you waive your 14-day right to cancel under the Consumer Contracts Regulations 2013 when you consent at checkout. This is confirmed via the checkbox before payment. If you experience a technical issue, contact us and we will resolve it.',
  },
  {
    q: 'Does HygieneFix work for businesses in Scotland?',
    a: 'Scotland uses the Food Hygiene Information Scheme (FHIS) with Pass/Improvement Required ratings rather than the 0–5 scale. HygieneFix can show your FHIS status, but our action plans are designed for the FHRS scoring system. Some guidance may not apply directly to Scottish inspections.',
  },
];

export default function FAQPage() {
  // FAQPage schema for Google rich results
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map((faq) => ({
      '@type': 'Question',
      name: faq.q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.a,
      },
    })),
  };

  return (
    <>
      <Header />
      <main className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />

        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-white/40 hover:text-white/60 transition-colors mb-8">
          ← Back to home
        </Link>

        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-xl bg-brand-blue/10 flex items-center justify-center">
            <HelpCircle className="w-5 h-5 text-brand-sky" />
          </div>
          <div>
            <h1 className="font-display text-2xl sm:text-3xl font-bold text-white">
              Frequently Asked Questions
            </h1>
            <p className="text-sm text-white/40">{FAQS.length} questions answered</p>
          </div>
        </div>

        <div className="space-y-4">
          {FAQS.map((faq, i) => (
            <div
              key={i}
              className="p-5 rounded-xl border border-white/5 bg-white/[0.02]"
            >
              <h2 className="text-sm font-semibold text-white/80 mb-2">{faq.q}</h2>
              <p className="text-sm text-white/45 leading-relaxed">{faq.a}</p>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="mt-10 p-6 rounded-2xl border border-brand-blue/20 bg-gradient-to-br from-brand-blue/10 to-brand-sky/5 text-center">
          <h3 className="font-display text-lg font-bold mb-2">Still have questions?</h3>
          <p className="text-sm text-white/40 mb-4">Check your rating for free, or get in touch.</p>
          <div className="flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/#search"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-brand-sky text-brand-navy text-sm font-bold hover:bg-brand-sky/90 transition-colors"
            >
              Check my rating <ArrowRight className="w-3.5 h-3.5" />
            </Link>
            <a
              href="mailto:support@hygienefix.co.uk"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-white/10 text-sm text-white/60 hover:bg-white/5 transition-colors"
            >
              Email support
            </a>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
